/// Flutter icons CustomIconsList
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconsList
///      fonts:
///       - asset: fonts/CustomIconsList.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIconsList {
  CustomIconsList._();

  static const _kFontFam = 'CustomIconsList';

  static const IconData favorites = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData placeholder = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData suitcase = IconData(0xe803, fontFamily: _kFontFam);
}
